# Generated by Django 4.1.3 on 2022-12-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='%Y_%m_%d/'),
        ),
    ]
